apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: flink-operator
spec:
  source: lightbend-operators
  sourceNamespace: flink
  name: lightbend-flink
  channel: alpha
  startingCSV: flinkoperator.v0.0.2
