# for creating these resources it requires the user to be logged in as system admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flink-operator-edit-resources
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: flink-operator
    namespace: default
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flink-operator
  labels: &default-labels
    app.kubernetes.io/name: flink-operator
    app.kubernetes.io/version: v0.1-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels: *default-labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *default-labels
    spec:
      serviceAccountName: flink-operator
      containers:
      - name: flink-operator
        image: lightbend/fdp-flink-operator:0.0.1
        env:
        - name: CRD
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        imagePullPolicy: IfNotPresent

