apiVersion: lightbend.com/v1
kind: FlinkCluster
metadata:
  namespace: nm
  name: my-flink-cluster
spec:
  metrics : true
  customImage : myimage
  labels:
    common-label-for-all-the-resources-operator-deploys/deployed-by: john
    common-label-to-be-replaced-on-some-resources: global-value
  env:
  - name: ENV1
    value: env1
  flinkConfiguration:
    num_taskmanagers: "2"
    taskmanagers_slots: "2"
    pullpolicy: "Always"
    parallelism: "2"
    logging : "flink-logging"
  worker:
    cpu: "2"
  master:
    cpu: "2"
    inputs:
    - input1
    - input2
  checkpointing:
    PVC : checkpvcname
    mountdirectory: checkdirectory
  savepointing:
    PVC : savepvcname
    mountdirectory: savedirectory
